/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring5.reactive.mongo.recipe.app;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
